PharmaMarket/blueprints/Drug/routes.py
from flask import render_template, request, Blueprint
from flask_login import login_required, current_user

from PharmaMarket.forms import FilterDrugForm, AddDrugForm, BuyDrugForm, RestockDrugForm
from PharmaMarket.models import Drug as DrugModel, DrugOrder
from PharmaMarket.queries import insert_drug, get_drug_by_pk, Sell, \
    insert_sell, get_all_drug_by_pharmacist, get_drug_by_filters, insert_drug_order, update_sell, \
    get_orders_by_customer_pk

Drug = Blueprint('Drug', __name__)

@Drug.route("/drug", methods=['GET', 'POST'])
def drug():
    form = FilterDrugForm()
    title = 'Our drug!'
    drug = []
    if request.method == 'POST':
        drug = get_drug_by_filters(name=request.form.get('name'),
                                   brand=request.form.get('brand'),
                                   city=request.form.get('city'),
                                   pharmacist_name=request.form.get('sold_by'),
                                   price=request.form.get('price'))
        title = f'Our {request.form.get("name")}!'
    return render_template('pages/drug.html', drug=drug, form=form, title=title)

@Drug.route("/add-drug", methods=['GET', 'POST'])
@login_required
def add_drug():
    form = AddDrugForm(
        data=dict(pharmacist_pk=current_user.pk))
    if request.method == 'POST':
        if form.validate_on_submit():
            drug_data = dict(
                id=form.id.data,
                name=form.name.data,
                brand=form.brand.data,
                city=form.city.data,
                price=form.price.data
            )
            drug = DrugModel(drug_data)
            new_drug_pk = insert_drug(drug)
            sell = Sell(dict(pharmacist_pk=current_user.pk, drug_pk=new_drug_pk, available=True))
            insert_sell(sell)
    return render_template('pages/add-drug.html', form=form)


@Drug.route("/your-drug", methods=['GET', 'POST'])
@login_required
def your_drug():
    form = FilterDrugForm()
    drug = []
    if request.method == 'GET':
        drug = get_all_drug_by_pharmacist(current_user.pk)
    if request.method == 'POST':
        drug = get_drug_by_filters(name=request.form.get('name'),
                                   brand=request.form.get('brand'),
                                   price=request.form.get('price'),
                                   pharmacist_pk=current_user.pk)
    return render_template('pages/your-drug.html', form=form, drug=drug)


@Drug.route('/drug/buy/<pk>', methods=['GET', 'POST'])
@login_required
def buy_drug(pk):
    form = BuyDrugForm()
    drug = get_drug_by_pk(pk)
    if request.method == 'POST':
        if form.validate_on_submit():
            order = DrugOrder(dict(drug_pk=drug.pk,
                                   pharmacist_pk=drug.pharmacist_pk,
                                   customer_pk=current_user.pk))
            insert_drug_order(order)
            update_sell(available=False,
                        drug_pk=drug.pk,
                        pharmacist_pk=drug.pharmacist_pk)
    return render_template('pages/buy-drug.html', form=form, drug=drug)


@Drug.route('/drug/restock/<pk>', methods=['GET', 'POST'])
@login_required
def restock_drug(pk):
    form = RestockDrugForm()
    drug = get_drug_by_pk(pk)
    if request.method == 'POST':
        if form.validate_on_submit():
            update_sell(available=True,
                        drug_pk=drug.pk,
                        pharmacist_pk=drug.pharmacist_pk)
    return render_template('pages/restock-drug.html', form=form, drug=drug)


@Drug.route('/drug/your-orders')
def your_orders():
    orders = get_orders_by_customer_pk(current_user.pk)
    return render_template('pages/your-orders.html', orders=orders)

PharmaMarket/blueprints/Login/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user

from PharmaMarket.forms import UserLoginForm, UserSignupForm
from PharmaMarket.models import Pharmacist, Customer
from PharmaMarket.queries import get_user_by_user_name, insert_pharmacist, insert_customer
from PharmaMarket.utils.choices import UserTypeChoices

Login = Blueprint('Login', __name__)


@Login.route("/")
@Login.route("/home")
def home():
    return render_template('pages/home.html')


@Login.route("/about")
def about():
    return render_template('pages/about.html')


@Login.route("/style-guide")
def style_guide():
    return render_template('pages/style-guide.html')


@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    form = UserLoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = get_user_by_user_name(form.user_name.data)
            if user and user['password'] == form.password.data:
                login_user(user, remember=True)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('Login.home'))
    return render_template('pages/login.html', form=form)


@Login.route("/signup", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    form = UserSignupForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user_data = dict(full_name=form.full_name.data,
                             user_name=form.user_name.data,
                             password=form.password.data)
            if form.user_type.data == UserTypeChoices.values()[0]:
                pharmacist = Pharmacist(user_data)
                insert_pharmacist(pharmacist)
            elif form.user_type.data == UserTypeChoices.values()[1]:
                customer = Customer(form.data)
                insert_customer(customer)
            user = get_user_by_user_name(form.user_name.data)
            if user:
                login_user(user, remember=True)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('Login.home'))
    return render_template('pages/signup.html', form=form)


@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Login.login'))

PharmaMarket/templates/components/footer.html
<footer>
    <div>
        <span>© PharmaMarket</span>
        <a href="{{ url_for('Login.style_guide') }}">Style Guide</a>
        <a href="{{ url_for('Login.about') }}">About</a>
    </div>
</footer>

PharmaMarket/templates/components/macros.html
{% macro cta_button (class='') %}
    <a class="btn {{ class }}" href="{{ url_for('Drug.drug') }}">
        <span>
            <img src="{{ url_for('static', filename='images/icons/cart.svg') }}" alt="cart" class="icon">
            Start shopping
        </span>
    </a>
{% endmacro %}




{% macro form_errors (errors=[]) %}
    {% for error in errors %}
        <span class="text--red">{{ error }}</span>
    {% endfor %}
{% endmacro %}



{% macro select_field (name='', choices=[]) %}
    <select name="{{ name }}" id="{{ name }}" aria-label="{{ name }}">
        <option value=null selected disabled>Choose an option...</option>
        {% for choice in choices %}
            <option value="{{ choice[0] }}">{{ choice[1] }}</option>
        {% endfor %}
        {{ form.id.options }}
    </select>
{% endmacro %}

{% macro filter_drug_form (form=None, sold_by=True) %}
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="form--row">
            <div class="form-group">
                {{ form.name.label }}
                {{ form.name }}
            </div>

            <div class="form-group">
                {{ form.brand.label }}
                {{ form.brand }}
            </div>

            <div class="form-group">
                {{ form.city.label }}
                {{ form.city }}
            </div>
        </div>

        <div class="form--row">
            {% if sold_by %}
                <div class="form-group">
                    {{ form.sold_by.label }}
                    {{ form.sold_by }}
                </div>
            {% endif %}

            <div class="form-group">
                {{ form.price.label }}
                {{ form.price }}
            </div>

            {{ form.submit(class="btn") }}
            <a href="{{ url_for('Drug.drug') }}" class="btn">Clear filters</a>
        </div>
    </form>
{% endmacro %}


{% macro drug_card (product=None, show_checkout=True, show_restock=False, date=None) %}
    <div class="card">
        <div class="card__info">
            {% if date %}
                <p>Date: {{ date }}</p>
            {% endif %}
            <p>Id: {{ product.id|format_data }}</p>
            <p>Name: {{ product.name|format_data }}</p>
            <p>Brand: {{ product.brand|format_data }}</p>
            <p>Price: £{{ product.price }} / {{ product.unit }}</p>
            {% if not date %}
                <p>In stock: {{ product.available }}</p>
                <p>Sold by: {{ product.pharmacist_name }}</p>
            {% endif %}
        </div>

        <div class="card__action">
            {% if show_checkout %}
                {% if product.available %}
                    <a href="{{ url_for('Drug.buy_drug', pk=product.drug_pk) }}">Buy</a>
                {% endif %}
            {% else %}
                {% if show_restock %}
                    {% if not product.available %}
                        <a href="{{ url_for('Drug.restock_drug', pk=product.drug_pk) }}">Restock</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endmacro %}

PharmaMarket/templates/components/navbar.html
<nav>
    <div>
        <div class="links-wrapper">
            <a href="{{ url_for("Login.home") }}">Home</a>
            <a href="{{ url_for("Drug.drug") }}">Buy Drugs</a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for("Drug.add_drug") }}">Add Drugs</a>
            <a href="{{ url_for("Drug.your_drug") }}">My Drugs</a>
            <a href="{{ url_for("Drug.your_orders") }}">My Orders</a>
            {% endif %}
        </div>

        <div class="links-wrapper">
            {% if current_user.is_authenticated %}
                <span class="text--gray">Logged in as: {{ current_user.user_name }}</span>
                <a href="{{ url_for("Login.logout") }}">Logout</a>
            {% else %}
                <a class="text--gray" href="{{ url_for("Login.signup") }}">Sign up</a>
                <a href="{{ url_for("Login.login") }}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>